# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the Vite dev server will run on
EXPOSE 3000

# Define the command to run the Vite dev server
CMD ["npm", "run", "dev","--","--host","0.0.0.0"]
